# Automated Windows (MSVC++) testing using appveyor.com
# https://ci.appveyor.com/projects

version: 1.0.{build}

branches:
  except:
    - gh-pages

os: Visual Studio 2017

platform:
  - x86
  - x64

build_script:
  - make
  - make instrumented_benchmark
  - make example